language: swift
osx_image: xcode9.2
xcode_project: StellarKit.xcodeproj
xcode_scheme: StellarKit
xcode_sdk: iphonesimulator8.4

before_script:
  - ./setup.sh

script:
  - curl -sS http://localhost:8000/accounts/GCLBBAIDP34M4JACPQJUYNSPZCQK7IRHV7ETKV6U53JPYYUIIVDVJJFQ
